import Head from 'next/head'
import Image from 'next/image'
import {
  homeStyles,
  imageWrapper,
  homeNav
} from '../styles/Home.module.css'

import homeImg from "../public/homes-large.png";

const Home = () => {
  return (
    <div className={ homeStyles }>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={ imageWrapper }>
        <Image
          src={ homeImg }
          alt="a picture of a terraced house"
          layout="fill"
          priority
        />
      </div>
      <header>
        <h1>The Market Place</h1>
        <nav className={ homeNav }>
          <ul>
            <li>Products</li>
            <li>Blog</li>
            <li>About</li>
          </ul>
        </nav>
      </header>
    </div>
  );
}

export default Home;
